name: example
description: A D_Server web application
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  d_server:
    path: ../
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  args: ^2.4.2
  yaml: ^3.1.2
  postgres: ^3.0.2
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
