server:
  host: localhost
  port: 3000
  environment: development

database:
  ssl: false
  host: localhost
  port: 5432
  database: example_development
  username: antran
  password: 1234

views:
  path: views
  default_layout: application

cors:
  enabled: true
  allow_origin: "*"

logging:
  level: info
  colors: true
  requests: true

hot_reload:
  enabled: true
  debounce_delay: 500
  watch_directories:
    - lib
    - views
  ignore_patterns:
    - "**/*.tmp"
    - "**/.*"
    - "**/.git/**"
