name: d_server
description: A web framework for Dart with Active Record ORM, RESTful routing, and built-in authentication
version: 0.3.0
license: Apache-2.0
publish_to: "none"
# homepage: https://github.com/your-username/d_server
# repository: https://github.com/your-username/d_server
# documentation: https://github.com/your-username/d_server/wiki

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.5
  postgres: ^3.5.9
  dart_template_engine:
    path: packages/dart_template_engine
  yaml: ^3.1.2
  watcher: ^1.1.0
  dart_jsonwebtoken: ^3.3.1
  crypto: ^3.0.3
  uuid: ^4.1.0
  bcrypt: ^1.1.3
  shelf_web_socket: ^3.0.0

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6

executables:
  d_server: d_server
