name: dart_template_engine
description: A powerful template engine for Dart with Mustache-like syntax and support for function calls
version: 1.0.0
license: Apache-2.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  petitparser: ^6.0.2

dev_dependencies:
  test: ^1.25.6
  lints: ^6.0.0

topics:
  - template-engine
  - mustache
  - html-templates
  - server-side-rendering
  - partials
